### ISSUE TITLE
README get_news rss_sources documentation is invalid

### ISSUE THREAD

**Issue by GrandMoff100** [FoxNerdSaysMoo/OpenNews#2]
:)

**Comment by FoxNerdSaysMoo** [comment]
Should be corrected, if not reopen this issue

**Comment by GrandMoff100** [comment]
In the future, you can create PR's that fix issues which are great for two reasons.

a) It makes it clear to mainainers, and other developers where and how the issue was fixed.

b) Using closing keywords, issues linked to PRs can be automaically closed when the PR is merged. Meaning you can also point people viewing issues to the PR where it was fixed.

Happy developing!
